POST https://api.perplexity.ai/search
Authorization: Bearer {{PERPLEXITY_API_KEY}}
Content-Type: application/json

{
  "query": [
   "Что такое flux"
  ]
}



###

POST https://api.perplexity.ai/chat/completions
Authorization: Bearer {{PERPLEXITY_API_KEY}}
Content-Type: application/json

{
  "model": "sonar-pro",
  "messages": [
    {
      "role": "user",
      "content": "«Какие основные разработки и анонсы в области искусственного интеллекта появились сегодня в технологической индустрии?»"
    }
  ]
}
